# Generated by Django 4.0.6 on 2022-08-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='certificate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='hobbies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
