# Generated by Django 4.1 on 2022-08-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_portfolio_links_alter_portfolio_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="Basic_information",
            field=models.TextField(blank=True),
        ),
    ]
