# Generated by Django 4.1 on 2022-08-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_portfolio_basic_information"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolio",
            old_name="certificate",
            new_name="certificate_work_experience",
        ),
    ]
