# Generated by Django 4.1 on 2022-08-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_rename_certificate_portfolio_certificate_work_experience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolio",
            old_name="certificate_work_experience",
            new_name="certificate_and_work_experience",
        ),
    ]
