# Generated by Django 4.0.6 on 2022-08-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_certificate_work_experience_portfolio_certificate_and_work_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='profile_images',
            new_name='portfolio_image',
        ),
    ]
